### PR TITLE
adjust references to ch-core profiles

### PR DESCRIPTION
**Pull request by oliveregger**

### CODE REVIEW

**Comment by oliveregger** [comment]
http://build.fhir.org/ig/hl7ch/ch-core/branches/stu2ballot-refcoreprofiles/index.html

**Comment by walterwellauer** [comment]
Review:
#100 OK
#101 OK - except identifier.assigner
#102 OK - maybe it could me made also in source.sourceReference, verified.verifiedWith and actor.reference
#103 issues:
- CH Core Organization Profile should probably be self referenced (to CH Core Organization Profile): identifier.assigner(various), partOf, endpoint
- the same for CH Core Organization Profile EPR
- CH Core Location: partOf
- CH Core Encounter: assigner (two of them), hospitalization.origin, hospitalization.destination, serviceProvider, partOf
- CH Core Document: identifier.assigner
- CH Core Document EPR: identifier.assigner
- CH Core Practitioner: identifier.assigner (various), qualifier.issuer
- the same for CH Core Practitioner EPR
- CH Core Patient: identifier.assigner (various), contact.organization, contact:contact.organization
- CH Core Composition EPR: identifier.assigner
(There might be good reasons why identifier.assigner (and similar) reference the base resources and not the CH Core [EPR] profiles)

**Comment by oliveregger** [comment]
hinzufügen von hospitalization.origin, hospitalization.destination, serviceProvider, partOf

guidelines next ballot: define policy that for all references which are in a differential the relationship to ch-core has to be profiled or not if there is a reason.

10 - 0 - 0

**Comment by walterwellauer** [comment]
hospitalization.origin, hospitalization.destination, serviceProvider, partOf look fine

**Pull request merged**
