### PR TITLE
improve accronyms definition #206

### PR DESCRIPTION
**Pull request by oliveregger**
see #206
- added the translations for practitioner / organization 
- for the values only english or translations when no english
- removed text narrative manual from naming system

### CODE REVIEW

**Comment by oliveregger** [comment]
http://build.fhir.org/ig/hl7ch/ch-core/branches/oe_lang_206/qa.html

http://build.fhir.org/ig/hl7ch/ch-core/branches/oe_lang_206/StructureDefinition-ch-core-practitioner.html

http://build.fhir.org/ig/hl7ch/ch-core/branches/oe_lang_206/StructureDefinition-ch-core-organization.html

**Review by qligier — APPROVED** [review]
Looks good to me, thanks!

Can't we link to the naming system in the resource? It is hard to find it otherwise.

**Comment by oliveregger** [comment]
the description in element short is of type string, we cannot add a link from there. I added it to definition (which is of type mark down), however this only shows up on the "Detailed Description Tab":
http://build.fhir.org/ig/hl7ch/ch-core/branches/oe_lang_206/StructureDefinition-ch-core-organization-definitions.html

**Comment by qligier** [comment]
Thank you, it is better like this.

**Comment by oliveregger** [comment]
Telco vom 1.3: 12 - 0 - 0

**Pull request merged**
